/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examenlab1_danielagurcia;

import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniel Agurcia
 */
public class Biblioteca_Virtual extends javax.swing.JFrame {

    /**
     * Creates new form Biblioteca_Virtual
     */
    public Biblioteca_Virtual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ventana_log_in = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        tf_username = new javax.swing.JTextField();
        tf_password = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jb_log_in = new javax.swing.JButton();
        ventana_sign_in = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jd_fecha_nacimiento = new com.toedter.calendar.JDateChooser();
        tf_password_sign = new javax.swing.JTextField();
        tf_username_sign = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tf_numeroTel = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tf_correo = new javax.swing.JTextField();
        tf_nombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cb_genero = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jb_sign_up = new javax.swing.JButton();
        ventana_log_in_admin = new javax.swing.JDialog();
        jb_admin_log = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tf_username_admin = new javax.swing.JTextField();
        tf_password_admin = new javax.swing.JTextField();
        Menu_usuario = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jb_agregar_libro_usuario = new javax.swing.JButton();
        cb_libros_disponibles = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jb_devolver_libro = new javax.swing.JButton();
        cb_devolver_libros = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        cb_lista_libros_disp_info = new javax.swing.JComboBox<>();
        jb_recibir_informacion = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel6 = new javax.swing.JPanel();
        jb_enviar_solicitud = new javax.swing.JButton();
        cb_lista_usuarios_amigos = new javax.swing.JComboBox<>();
        jPanel4 = new javax.swing.JPanel();
        cb_libros_usuario_prestar = new javax.swing.JComboBox<>();
        cb_lista_amigos = new javax.swing.JComboBox<>();
        jb_prestar_libro = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        cb_lista_libros_genFav = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        cb_lista_solicitudes = new javax.swing.JComboBox<>();
        jb_rechazar_solicitud = new javax.swing.JButton();
        jb_aceptar_solicitud = new javax.swing.JButton();
        Menu_admin = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_descripcion = new javax.swing.JTextArea();
        tf_titulo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        sp_puntaje = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        sp_copias = new javax.swing.JSpinner();
        cb_genero_libros = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        tf_valor = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tf_edicion = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jd_publicacion = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        tf_nombreAutor = new javax.swing.JTextField();
        jb_agregar_libro = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jb_modificar_Libros = new javax.swing.JButton();
        cb_modificar = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jb_eliminar_libros = new javax.swing.JButton();
        cb_eliminar = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        cb_historial = new javax.swing.JComboBox<>();
        Ventana_Modificar = new javax.swing.JDialog();
        rb_titulo = new javax.swing.JRadioButton();
        rb_desc = new javax.swing.JRadioButton();
        rb_puntaje = new javax.swing.JRadioButton();
        rb_copias = new javax.swing.JRadioButton();
        rb_genero = new javax.swing.JRadioButton();
        rb_valor = new javax.swing.JRadioButton();
        rb_edicion = new javax.swing.JRadioButton();
        rb_autor = new javax.swing.JRadioButton();
        rb_public = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        jb_modi_ele = new javax.swing.JButton();
        bg_modificar = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel1.setText("Username");

        tf_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_usernameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel2.setText("Password");

        jb_log_in.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jb_log_in.setText("Log In");
        jb_log_in.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_log_inMouseClicked(evt);
            }
        });
        jb_log_in.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_log_inActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventana_log_inLayout = new javax.swing.GroupLayout(ventana_log_in.getContentPane());
        ventana_log_in.getContentPane().setLayout(ventana_log_inLayout);
        ventana_log_inLayout.setHorizontalGroup(
            ventana_log_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventana_log_inLayout.createSequentialGroup()
                .addGroup(ventana_log_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventana_log_inLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(ventana_log_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ventana_log_inLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10)
                                .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ventana_log_inLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(15, 15, 15)
                                .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ventana_log_inLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jb_log_in)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        ventana_log_inLayout.setVerticalGroup(
            ventana_log_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventana_log_inLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(ventana_log_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventana_log_inLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(ventana_log_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_password, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_log_in)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 48)); // NOI18N
        jLabel3.setText("Sign In");

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setText("Contrasenia");

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setText("Username");

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setText("Fecha de Nacimiento");

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setText("Numero Telefonico");

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setText("Correo Electronico");

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel10.setText("Nombre Completo");

        cb_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fantasia", "Romance", "Accion", "Historia" }));

        jLabel11.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel11.setText("Genero Favorito");

        jb_sign_up.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jb_sign_up.setText("Sign up");
        jb_sign_up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_sign_upMouseClicked(evt);
            }
        });
        jb_sign_up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_sign_upActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventana_sign_inLayout = new javax.swing.GroupLayout(ventana_sign_in.getContentPane());
        ventana_sign_in.getContentPane().setLayout(ventana_sign_inLayout);
        ventana_sign_inLayout.setHorizontalGroup(
            ventana_sign_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventana_sign_inLayout.createSequentialGroup()
                .addGroup(ventana_sign_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventana_sign_inLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jLabel3))
                    .addGroup(ventana_sign_inLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel10)
                        .addGap(6, 6, 6)
                        .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventana_sign_inLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel5)
                        .addGap(13, 13, 13)
                        .addComponent(tf_password_sign, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventana_sign_inLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(tf_username_sign, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventana_sign_inLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel7)
                        .addGap(11, 11, 11)
                        .addComponent(jd_fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventana_sign_inLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel8)
                        .addGap(8, 8, 8)
                        .addComponent(tf_numeroTel, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventana_sign_inLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel9)
                        .addGap(11, 11, 11)
                        .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventana_sign_inLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel11)
                        .addGap(10, 10, 10)
                        .addComponent(cb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ventana_sign_inLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jb_sign_up, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        ventana_sign_inLayout.setVerticalGroup(
            ventana_sign_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventana_sign_inLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(58, 58, 58)
                .addGroup(ventana_sign_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(ventana_sign_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(tf_password_sign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(ventana_sign_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(tf_username_sign, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(ventana_sign_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jd_fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(ventana_sign_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(tf_numeroTel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(ventana_sign_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(ventana_sign_inLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(cb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jb_sign_up)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jb_admin_log.setText("Log In");
        jb_admin_log.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_admin_logMouseClicked(evt);
            }
        });

        jLabel12.setText("Usuario del Administrador");

        jLabel13.setText("Contrasenia");

        javax.swing.GroupLayout ventana_log_in_adminLayout = new javax.swing.GroupLayout(ventana_log_in_admin.getContentPane());
        ventana_log_in_admin.getContentPane().setLayout(ventana_log_in_adminLayout);
        ventana_log_in_adminLayout.setHorizontalGroup(
            ventana_log_in_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventana_log_in_adminLayout.createSequentialGroup()
                .addGroup(ventana_log_in_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventana_log_in_adminLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(ventana_log_in_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventana_log_in_adminLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(44, 44, 44)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ventana_log_in_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_username_admin)
                            .addComponent(tf_password_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ventana_log_in_adminLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jb_admin_log)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        ventana_log_in_adminLayout.setVerticalGroup(
            ventana_log_in_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventana_log_in_adminLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(ventana_log_in_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tf_username_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ventana_log_in_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(tf_password_admin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jb_admin_log)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Menu_usuario.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jb_agregar_libro_usuario.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jb_agregar_libro_usuario.setText("Agregar");
        jb_agregar_libro_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregar_libro_usuarioMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(cb_libros_disponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jb_agregar_libro_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(cb_libros_disponibles, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jb_agregar_libro_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addGap(135, 135, 135))
        );

        jTabbedPane1.addTab("Agregar un Libro", jPanel1);

        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        jb_devolver_libro.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jb_devolver_libro.setText("Devolver");
        jb_devolver_libro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_devolver_libroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(cb_devolver_libros, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jb_devolver_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(cb_devolver_libros, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_devolver_libro, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Devolver Libros", jPanel2);

        jb_recibir_informacion.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jb_recibir_informacion.setText("Recibir Informacion");
        jb_recibir_informacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_recibir_informacionMouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_recibir_informacion, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                    .addComponent(cb_lista_libros_disp_info, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cb_lista_libros_disp_info, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jb_recibir_informacion)
                        .addContainerGap(145, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane4)
                        .addGap(19, 19, 19))))
        );

        jTabbedPane1.addTab("Informacion de los Libros", jPanel3);

        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jb_enviar_solicitud.setText("Enviar Solicitud");
        jb_enviar_solicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_enviar_solicitudMouseClicked(evt);
            }
        });
        jPanel6.add(jb_enviar_solicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 150, 70));

        jPanel6.add(cb_lista_usuarios_amigos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 220, 60));

        jTabbedPane1.addTab("Agregar Amigos", jPanel6);

        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.add(cb_libros_usuario_prestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 160, 50));

        jPanel4.add(cb_lista_amigos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 170, 50));

        jb_prestar_libro.setText("Prestar Libro");
        jb_prestar_libro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_prestar_libroMouseClicked(evt);
            }
        });
        jPanel4.add(jb_prestar_libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 170, 40));

        jTabbedPane1.addTab("Prestar Libros", jPanel4);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(cb_lista_libros_genFav, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(cb_lista_libros_genFav, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lista de Libros", jPanel7);

        jPanel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel12MouseClicked(evt);
            }
        });
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.add(cb_lista_solicitudes, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 30, 186, 51));

        jb_rechazar_solicitud.setBackground(new java.awt.Color(204, 0, 51));
        jb_rechazar_solicitud.setForeground(new java.awt.Color(102, 0, 0));
        jb_rechazar_solicitud.setText("Rechazar");
        jb_rechazar_solicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_rechazar_solicitudMouseClicked(evt);
            }
        });
        jPanel12.add(jb_rechazar_solicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 117, 53));

        jb_aceptar_solicitud.setBackground(new java.awt.Color(0, 255, 51));
        jb_aceptar_solicitud.setForeground(new java.awt.Color(0, 102, 51));
        jb_aceptar_solicitud.setText("Agregar");
        jb_aceptar_solicitud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_aceptar_solicitudMouseClicked(evt);
            }
        });
        jb_aceptar_solicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_aceptar_solicitudActionPerformed(evt);
            }
        });
        jPanel12.add(jb_aceptar_solicitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 120, 50));

        jTabbedPane1.addTab("Solicitudes de Amistad", jPanel12);

        Menu_usuario.getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 470, -1));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Titulo");
        jPanel9.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        ta_descripcion.setColumns(20);
        ta_descripcion.setRows(5);
        jScrollPane1.setViewportView(ta_descripcion);

        jPanel9.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));
        jPanel9.add(tf_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 140, -1));

        jLabel14.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel14.setText("Descripcion");
        jPanel9.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        sp_puntaje.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        sp_puntaje.setToolTipText("");
        jPanel9.add(sp_puntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 60, -1));

        jLabel15.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel15.setText("Puntaje");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel16.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel16.setText("Copias Disp.");
        jPanel9.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        sp_copias.setModel(new javax.swing.SpinnerNumberModel());
        jPanel9.add(sp_copias, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 60, -1));

        cb_genero_libros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fantasia", "Romance", "Accion", "Historia" }));
        jPanel9.add(cb_genero_libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 100, -1));

        jLabel17.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel17.setText("Genero");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 275, -1, -1));

        jLabel18.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel18.setText("Valor");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));
        jPanel9.add(tf_valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 70, -1));

        jLabel19.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel19.setText("Edicion");
        jPanel9.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));
        jPanel9.add(tf_edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 100, 120, -1));

        jLabel20.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel20.setText("Anio Publicacion");
        jPanel9.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, -1, -1));
        jPanel9.add(jd_publicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, 150, -1));

        jLabel21.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel21.setText("Autor");
        jPanel9.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, -1, -1));
        jPanel9.add(tf_nombreAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 150, -1));

        jb_agregar_libro.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jb_agregar_libro.setText("Agregar Libro");
        jb_agregar_libro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_agregar_libroMouseClicked(evt);
            }
        });
        jPanel9.add(jb_agregar_libro, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 250, 190, 70));

        jTabbedPane2.addTab("Agregar Libros", jPanel9);

        jb_modificar_Libros.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jb_modificar_Libros.setText("Modificar");
        jb_modificar_Libros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modificar_LibrosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_modificar_Libros, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(396, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(cb_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_modificar_Libros, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(172, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Modificar Libros", jPanel10);

        jb_eliminar_libros.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jb_eliminar_libros.setText("Eliminar");
        jb_eliminar_libros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_eliminar_librosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cb_eliminar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_eliminar_libros, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addContainerGap(409, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(cb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_eliminar_libros, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Eliminar Libros", jPanel11);

        cb_historial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(cb_historial, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(cb_historial, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Historial", jPanel5);

        javax.swing.GroupLayout Menu_adminLayout = new javax.swing.GroupLayout(Menu_admin.getContentPane());
        Menu_admin.getContentPane().setLayout(Menu_adminLayout);
        Menu_adminLayout.setHorizontalGroup(
            Menu_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        Menu_adminLayout.setVerticalGroup(
            Menu_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );

        bg_modificar.add(rb_titulo);
        rb_titulo.setText("Titulo");

        bg_modificar.add(rb_desc);
        rb_desc.setText("Descripion");

        bg_modificar.add(rb_puntaje);
        rb_puntaje.setText("Puntaje");

        bg_modificar.add(rb_copias);
        rb_copias.setText("Copias disponibles");

        bg_modificar.add(rb_genero);
        rb_genero.setText("Genero");

        bg_modificar.add(rb_valor);
        rb_valor.setText("Valor");

        bg_modificar.add(rb_edicion);
        rb_edicion.setText("Edicion");

        bg_modificar.add(rb_autor);
        rb_autor.setText("Autor");
        rb_autor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_autorActionPerformed(evt);
            }
        });

        bg_modificar.add(rb_public);
        rb_public.setText("Anio de Publicacion");
        rb_public.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_publicActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel22.setText("Seleccione lo que quiere modificar");

        jb_modi_ele.setText("Modificar Elemento");
        jb_modi_ele.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_modi_eleMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Ventana_ModificarLayout = new javax.swing.GroupLayout(Ventana_Modificar.getContentPane());
        Ventana_Modificar.getContentPane().setLayout(Ventana_ModificarLayout);
        Ventana_ModificarLayout.setHorizontalGroup(
            Ventana_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Ventana_ModificarLayout.createSequentialGroup()
                .addGroup(Ventana_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Ventana_ModificarLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel22))
                    .addGroup(Ventana_ModificarLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(Ventana_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb_public)
                            .addComponent(rb_autor)
                            .addComponent(rb_edicion)
                            .addComponent(rb_valor)
                            .addComponent(rb_genero)
                            .addComponent(rb_copias)
                            .addComponent(rb_puntaje)
                            .addComponent(rb_desc)
                            .addComponent(rb_titulo)))
                    .addGroup(Ventana_ModificarLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jb_modi_ele, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        Ventana_ModificarLayout.setVerticalGroup(
            Ventana_ModificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Ventana_ModificarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_desc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_puntaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_copias)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rb_genero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_valor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_edicion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_autor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb_public)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_modi_ele, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jButton1.setText("Sign In");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jButton2.setText("Log In");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("sansserif", 0, 36)); // NOI18N
        jButton3.setText("Sign In ADMIN");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        ventana_log_in.setModal(true);
        ventana_log_in.pack();
        ventana_log_in.setLocationRelativeTo(this);
        ventana_log_in.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        ventana_sign_in.setModal(true);
        ventana_sign_in.pack();
        ventana_sign_in.setLocationRelativeTo(this);
        ventana_sign_in.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        ventana_log_in_admin.setModal(true);
        ventana_log_in_admin.pack();
        ventana_log_in_admin.setLocationRelativeTo(this);
        ventana_log_in_admin.setVisible(true);
    }//GEN-LAST:event_jButton3MouseClicked

    private void tf_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_usernameActionPerformed

    }//GEN-LAST:event_tf_usernameActionPerformed

    private void jb_sign_upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_sign_upActionPerformed

    }//GEN-LAST:event_jb_sign_upActionPerformed

    private void jb_log_inActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_log_inActionPerformed

    }//GEN-LAST:event_jb_log_inActionPerformed

    private void jb_log_inMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_log_inMouseClicked
        try {
            String user = tf_username.getText();
            String pass = tf_password.getText();
            boolean log = false;
            for (Usuario temp : lista_usuarios) {
                if (temp.getUsername().equals(user) && temp.getPassword().equals(pass)) {
                    log = true;
                    usuario_ingresado = temp;
                }
            }
            if (log == true) {
                ventana_log_in.dispose();
                Menu_usuario.setModal(true);
                Menu_usuario.pack();
                Menu_usuario.setLocationRelativeTo(this);
                Menu_usuario.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o Contrasena Incorrecto");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un erro y no se ingresaron los datos");
        }
    }//GEN-LAST:event_jb_log_inMouseClicked

    private void jb_sign_upMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_sign_upMouseClicked
        try {
            String nombre = tf_nombre.getText();
            String user = tf_username_sign.getText();
            String pass = tf_password_sign.getText();
            Date fecha = jd_fecha_nacimiento.getDate();
            int numero_telefonico = Integer.parseInt(tf_numeroTel.getText());
            String correo = tf_correo.getText();
            String genero = cb_genero.getSelectedItem().toString();
            Usuario nuevoUsuario = new Usuario(nombre, user, pass, fecha, numero_telefonico, correo, genero);
            lista_usuarios.add(nuevoUsuario);
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_lista_usuarios_amigos.getModel();
            modelo.addElement(nuevoUsuario);
            cb_lista_usuarios_amigos.setModel(modelo);
            tf_nombre.setText("");
            tf_username_sign.setText("");
            tf_password_sign.setText("");
            jd_fecha_nacimiento.setDate(new Date());
            tf_numeroTel.setText("");
            tf_correo.setText("");
            cb_genero.setSelectedItem(false);
            JOptionPane.showMessageDialog(this, "Usuario Registrado Correctamente");
            ventana_sign_in.dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un erro y no se ingresaron los datos");
        }
    }//GEN-LAST:event_jb_sign_upMouseClicked

    private void jb_admin_logMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_admin_logMouseClicked
        try {
            String user = tf_username_admin.getText();
            String pass = tf_password_admin.getText();
            boolean log = false;
            if (user.equals("papiagurcia") && pass.equals("12345")) {
                log = true;
                ventana_log_in_admin.dispose();
                JOptionPane.showMessageDialog(this, "Bienvenido Admin PapiAgurcia");
                Menu_admin.setModal(true);
                Menu_admin.pack();
                Menu_admin.setLocationRelativeTo(this);
                Menu_admin.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contrasenia Incorrecta, Porfavor revise el archivo de texto enviado");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un erro y no se ingresaron los datos");
        }
    }//GEN-LAST:event_jb_admin_logMouseClicked

    private void jb_agregar_libroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregar_libroMouseClicked
        try {
            String titulo = tf_titulo.getText();
            String Descripcion = ta_descripcion.getText();
            int puntaje = (Integer) sp_puntaje.getValue();
            int copias = (Integer) sp_copias.getValue();
            String genero = cb_genero_libros.getSelectedItem().toString();
            double valor = Double.parseDouble(tf_valor.getText());
            int edicion = Integer.parseInt(tf_edicion.getText());
            String autor = tf_nombreAutor.getText();
            Date fecha_publi = jd_publicacion.getDate();
            Libro nuevoLibro = new Libro(titulo, Descripcion, puntaje, copias, genero, ERROR, edicion, autor, fecha_publi);
            lista_libros_Principal.add(nuevoLibro);
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_libros_disponibles.getModel();
            modelo.addElement(nuevoLibro);
            cb_libros_disponibles.setModel(modelo);
            DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_lista_libros_disp_info.getModel();
            modelo2.addElement(nuevoLibro);
            cb_lista_libros_disp_info.setModel(modelo2);
            DefaultComboBoxModel modelo4 = (DefaultComboBoxModel) cb_modificar.getModel();
            modelo4.addElement(nuevoLibro);
            cb_modificar.setModel(modelo4);
            DefaultComboBoxModel modelo5 = (DefaultComboBoxModel) cb_eliminar.getModel();
            modelo5.addElement(nuevoLibro);
            cb_eliminar.setModel(modelo5);
            tf_titulo.setText("");
            ta_descripcion.setText("");
            sp_puntaje.setValue(1);
            sp_copias.setValue(0);
            cb_genero_libros.setSelectedItem(false);
            tf_valor.setText("");
            tf_edicion.setText("");
            tf_nombreAutor.setText("");
            jd_publicacion.setDate(new Date());
            JOptionPane.showMessageDialog(this, "Libro Registrado Correctamente");
            DefaultComboBoxModel modelo6 = (DefaultComboBoxModel) cb_historial.getModel();
            modelo6.addElement("Se agrego un libro en la lista de libros principal");
            cb_historial.setModel(modelo6);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un erro y no se ingresaron los datos");
        }
    }//GEN-LAST:event_jb_agregar_libroMouseClicked

    private void jb_recibir_informacionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_recibir_informacionMouseClicked
        try {
            ta_descripcion.setText("");
            Libro seleccion = (Libro) cb_lista_libros_disp_info.getSelectedItem();
            ta_descripcion.setText(seleccion.toString2());
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_historial.getModel();
            modelo.addElement("Se Recibio la informacion de un libro");
            cb_historial.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un erro y no se ingresaron los datos");
        }
    }//GEN-LAST:event_jb_recibir_informacionMouseClicked

    private void jb_devolver_libroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_devolver_libroMouseClicked
        try {
            Libro seleccion = (Libro) cb_devolver_libros.getSelectedItem();
            usuario_ingresado.getLibros_usuario().remove(seleccion);
//        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_libros_usuario_prestar.getModel();
//        modelo.removeElement(seleccion);
//        cb_libros_usuario_prestar.setModel(modelo);
//        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_devolver_libros.getModel();
//        modelo2.removeElement(seleccion);
//        cb_devolver_libros.setModel(modelo2);
            if (usuario_ingresado.getGenero_fav().equals(seleccion.getGenero())) {
                DefaultComboBoxModel modelo3 = (DefaultComboBoxModel) cb_lista_libros_genFav.getModel();
                modelo3.removeElement(seleccion);
                cb_lista_libros_genFav.setModel(modelo3);
            }
            JOptionPane.showMessageDialog(this, "Libro eliminado exitosamente");
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_historial.getModel();
            modelo.addElement("Un usuario devolvio un libro");
            cb_historial.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un erro y no se ingresaron los datos");
        }
    }//GEN-LAST:event_jb_devolver_libroMouseClicked

    private void jb_agregar_libro_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_agregar_libro_usuarioMouseClicked
        try {
            Libro seleccion = (Libro) cb_libros_disponibles.getSelectedItem();
            usuario_ingresado.getLibros_usuario().add(seleccion);
//        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_libros_usuario_prestar.getModel();
//        modelo.addElement(seleccion);
//        cb_libros_usuario_prestar.setModel(modelo);
//        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_devolver_libros.getModel();
//        modelo2.addElement(seleccion);
//        cb_devolver_libros.setModel(modelo2);
            if (usuario_ingresado.getGenero_fav().equals(seleccion.getGenero())) {
                DefaultComboBoxModel modelo3 = (DefaultComboBoxModel) cb_lista_libros_genFav.getModel();
                modelo3.addElement(seleccion);
                cb_lista_libros_genFav.setModel(modelo3);
            }
            JOptionPane.showMessageDialog(this, "Libro agregado exitosamente");
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_historial.getModel();
            modelo.addElement("Un usuario agrego un libro");
            cb_historial.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un erro y no se ingresaron los datos");
        }
    }//GEN-LAST:event_jb_agregar_libro_usuarioMouseClicked

    private void jb_aceptar_solicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_aceptar_solicitudMouseClicked
        try {
            Usuario seleccion = (Usuario) cb_lista_solicitudes.getSelectedItem();
            usuario_ingresado.getLista_amigos().add(seleccion);
//        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_lista_amigos.getModel();
//        modelo.addElement(seleccion);
//        cb_lista_amigos.setModel(modelo);
//        DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_lista_solicitudes.getModel();
//        modelo2.removeElement(seleccion);
//        cb_lista_solicitudes.setModel(modelo2);
//        DefaultComboBoxModel modelo3 = (DefaultComboBoxModel) cb_lista_amigos.getModel();
//        modelo3.addElement(seleccion);
//        cb_lista_amigos.setModel(modelo3);
            JOptionPane.showMessageDialog(this, "Solicitud de amistad acepatada correctamente");
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_historial.getModel();
            modelo.addElement("Un usuario acepto una solicitud de amistad");
            cb_historial.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un erro y no se ingresaron los datos");
        }
    }//GEN-LAST:event_jb_aceptar_solicitudMouseClicked

    private void jb_rechazar_solicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_rechazar_solicitudMouseClicked
        try {
            Usuario seleccion = (Usuario) cb_lista_solicitudes.getSelectedItem();
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_lista_solicitudes.getModel();
            modelo.removeElement(seleccion);
            cb_lista_solicitudes.setModel(modelo);
            JOptionPane.showMessageDialog(this, "Solicitud de amistad rechazada correctamente");
            DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_historial.getModel();
            modelo2.addElement("Un usuario rechazo una solicitud de amistad");
            cb_historial.setModel(modelo2);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un erro y no se ingresaron los datos");
        }
    }//GEN-LAST:event_jb_rechazar_solicitudMouseClicked

    private void jb_enviar_solicitudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_enviar_solicitudMouseClicked
        try {
            Usuario seleccion = (Usuario) cb_lista_usuarios_amigos.getSelectedItem();
            seleccion.getLista_solicitudes().add(usuario_ingresado);
            JOptionPane.showMessageDialog(this, "Solicitud de amistad enviada correctamente");
            DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_historial.getModel();
            modelo.addElement("Un usuario envio una solicitud de amistad");
            cb_historial.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un erro y no se ingresaron los datos");
        }
    }//GEN-LAST:event_jb_enviar_solicitudMouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_lista_solicitudes.getModel();
        for (Usuario temp : usuario_ingresado.getLista_solicitudes()) {
            modelo.addElement(temp);
        }
        cb_lista_solicitudes.setModel(modelo);
    }//GEN-LAST:event_jPanel6MouseClicked

    private void jb_aceptar_solicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_aceptar_solicitudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_aceptar_solicitudActionPerformed

    private void jb_prestar_libroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_prestar_libroMouseClicked
        try {
            Usuario amigo_seleccionado = (Usuario) cb_lista_amigos.getSelectedItem();
            Libro libro_prestado = (Libro) cb_libros_usuario_prestar.getSelectedItem();
            if (amigo_seleccionado != null && libro_prestado != null) {
                amigo_seleccionado.getLibros_usuario().add(libro_prestado);
                usuario_ingresado.getLibros_usuario().remove(libro_prestado);
                JOptionPane.showMessageDialog(this, "Libro Prestado exitosamente");
                DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_historial.getModel();
                modelo.addElement("Un usuario presto un libro");
                cb_historial.setModel(modelo);
            } else {
                JOptionPane.showMessageDialog(this, "Seleccione un amigo y un Libro");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un erro y no se ingresaron los datos");
        }

    }//GEN-LAST:event_jb_prestar_libroMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void jPanel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel12MouseClicked
    }//GEN-LAST:event_jPanel12MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        DefaultComboBoxModel modelo3 = (DefaultComboBoxModel) cb_lista_amigos.getModel();
        for (Usuario temp : usuario_ingresado.getLista_amigos()) {
            modelo3.addElement(temp);
        }
        cb_lista_amigos.setModel(modelo3);
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cb_libros_usuario_prestar.getModel();
        for (Libro temp : usuario_ingresado.getLibros_usuario()) {
            modelo.addElement(temp);
        }
        cb_libros_usuario_prestar.setModel(modelo);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked

        for (Libro temp : usuario_ingresado.getLibros_usuario()) {
            DefaultComboBoxModel modelo2 = (DefaultComboBoxModel) cb_devolver_libros.getModel();
            modelo2.addElement(temp);
            cb_devolver_libros.setModel(modelo2);
        }

    }//GEN-LAST:event_jPanel2MouseClicked

    private void jb_modificar_LibrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modificar_LibrosMouseClicked
        seleccion_modi = (Libro) cb_modificar.getSelectedItem();
        Ventana_Modificar.setModal(true);
        Ventana_Modificar.pack();
        Ventana_Modificar.setLocationRelativeTo(this);
        Ventana_Modificar.setVisible(true);

    }//GEN-LAST:event_jb_modificar_LibrosMouseClicked

    private void jb_eliminar_librosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_eliminar_librosMouseClicked
        Libro seleccion = (Libro) cb_eliminar.getSelectedItem();
        lista_libros_Principal.remove(seleccion);
        JOptionPane.showMessageDialog(this, "Se elimino el libro exitosamente");
    }//GEN-LAST:event_jb_eliminar_librosMouseClicked

    private void rb_autorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_autorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_autorActionPerformed

    private void rb_publicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_publicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_publicActionPerformed

    private void jb_modi_eleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_modi_eleMouseClicked
        if (rb_titulo.isSelected()) {
            String newtitulo = JOptionPane.showInputDialog(this, "Ingrese el nuevo titulo");
            seleccion_modi.setTitulo(newtitulo);
            JOptionPane.showMessageDialog(this, "Se modifico el titulo exitosamente");
        } else if (rb_autor.isSelected()) {
            String newautor = JOptionPane.showInputDialog(this, "Ingrese el nuevo nombre del autor");
            seleccion_modi.setAutor(newautor);
            JOptionPane.showMessageDialog(this, "Se modifico el autor exitosamente");
        } else if (rb_puntaje.isSelected()) {
            String newpuntajeS = JOptionPane.showInputDialog(this, "Ingrese el nuevo puntaje");
            int newpuntaje = Integer.parseInt(newpuntajeS);
            if (newpuntaje <= 0 || newpuntaje > 5) {
                JOptionPane.showMessageDialog(this, "no puede ser menor de 0 ni mayor a 5");
                newpuntajeS = JOptionPane.showInputDialog(this, "Ingrese el nuevo puntaje");
                newpuntaje = Integer.parseInt(newpuntajeS);
            }
            seleccion_modi.setPuntaje(newpuntaje);
            JOptionPane.showMessageDialog(this, "Se modifico el puntaje exitosamente");
        } else if (rb_public.isSelected()) {
            String newfecha = JOptionPane.showInputDialog(this, "Ingrese la nueva fecha");
            seleccion_modi.setAnio_publicacion(new Date());
            JOptionPane.showMessageDialog(this, "Se modifico la fecha exitosamente");
        } else if (rb_genero.isSelected()) {
            String newgenero = JOptionPane.showInputDialog(this, "Ingrese el nuevo genero del libro\n1)Fantasia\n2)Romance\n3)Accion\n4)Historia");
            seleccion_modi.setGenero(newgenero);
            JOptionPane.showMessageDialog(this, "Se modifico el genero exitosamente");
        } else if (rb_edicion.isSelected()) {
            String newedicionS = JOptionPane.showInputDialog(this, "Ingrese la nuevo edicion");
            int newedicion = Integer.parseInt(newedicionS);
            seleccion_modi.setEdicion(newedicion);
            JOptionPane.showMessageDialog(this, "Se modifico la Edicion exitosamente");
        } else if (rb_desc.isSelected()) {
            String newdesc = JOptionPane.showInputDialog(this, "Ingrese la nueva descripcion del libro");
            seleccion_modi.setDescripcion(newdesc);
            JOptionPane.showMessageDialog(this, "Se modifico la descripcion exitosamente");
        } else if (rb_copias.isSelected()) {
            String newcopiasS = JOptionPane.showInputDialog(this, "Ingrese las nuevas copias");
            int newcopias = Integer.parseInt(newcopiasS);
            seleccion_modi.setCopias_disponibles(newcopias);
            JOptionPane.showMessageDialog(this, "Se modifico las copias exitosamente");
        }
    }//GEN-LAST:event_jb_modi_eleMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biblioteca_Virtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biblioteca_Virtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biblioteca_Virtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca_Virtual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca_Virtual().setVisible(true);
            }
        });
    }
    //////////////////////////////////////////////////////////
    ArrayList<Libro> lista_libros_Principal = new ArrayList();
    ArrayList<Usuario> lista_usuarios = new ArrayList();
    Usuario usuario_ingresado;
    Libro seleccion_modi;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Menu_admin;
    private javax.swing.JDialog Menu_usuario;
    private javax.swing.JDialog Ventana_Modificar;
    private javax.swing.ButtonGroup bg_modificar;
    private javax.swing.JComboBox<String> cb_devolver_libros;
    private javax.swing.JComboBox<String> cb_eliminar;
    private javax.swing.JComboBox<String> cb_genero;
    private javax.swing.JComboBox<String> cb_genero_libros;
    private javax.swing.JComboBox<String> cb_historial;
    private javax.swing.JComboBox<String> cb_libros_disponibles;
    private javax.swing.JComboBox<String> cb_libros_usuario_prestar;
    private javax.swing.JComboBox<String> cb_lista_amigos;
    private javax.swing.JComboBox<String> cb_lista_libros_disp_info;
    private javax.swing.JComboBox<String> cb_lista_libros_genFav;
    private javax.swing.JComboBox<String> cb_lista_solicitudes;
    private javax.swing.JComboBox<String> cb_lista_usuarios_amigos;
    private javax.swing.JComboBox<String> cb_modificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jb_aceptar_solicitud;
    private javax.swing.JButton jb_admin_log;
    private javax.swing.JButton jb_agregar_libro;
    private javax.swing.JButton jb_agregar_libro_usuario;
    private javax.swing.JButton jb_devolver_libro;
    private javax.swing.JButton jb_eliminar_libros;
    private javax.swing.JButton jb_enviar_solicitud;
    private javax.swing.JButton jb_log_in;
    private javax.swing.JButton jb_modi_ele;
    private javax.swing.JButton jb_modificar_Libros;
    private javax.swing.JButton jb_prestar_libro;
    private javax.swing.JButton jb_rechazar_solicitud;
    private javax.swing.JButton jb_recibir_informacion;
    private javax.swing.JButton jb_sign_up;
    private com.toedter.calendar.JDateChooser jd_fecha_nacimiento;
    private com.toedter.calendar.JDateChooser jd_publicacion;
    private javax.swing.JRadioButton rb_autor;
    private javax.swing.JRadioButton rb_copias;
    private javax.swing.JRadioButton rb_desc;
    private javax.swing.JRadioButton rb_edicion;
    private javax.swing.JRadioButton rb_genero;
    private javax.swing.JRadioButton rb_public;
    private javax.swing.JRadioButton rb_puntaje;
    private javax.swing.JRadioButton rb_titulo;
    private javax.swing.JRadioButton rb_valor;
    private javax.swing.JSpinner sp_copias;
    private javax.swing.JSpinner sp_puntaje;
    private javax.swing.JTextArea ta_descripcion;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_edicion;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombreAutor;
    private javax.swing.JTextField tf_numeroTel;
    private javax.swing.JTextField tf_password;
    private javax.swing.JTextField tf_password_admin;
    private javax.swing.JTextField tf_password_sign;
    private javax.swing.JTextField tf_titulo;
    private javax.swing.JTextField tf_username;
    private javax.swing.JTextField tf_username_admin;
    private javax.swing.JTextField tf_username_sign;
    private javax.swing.JTextField tf_valor;
    private javax.swing.JDialog ventana_log_in;
    private javax.swing.JDialog ventana_log_in_admin;
    private javax.swing.JDialog ventana_sign_in;
    // End of variables declaration//GEN-END:variables
}
